[General]
background=assets/background.jpg
blur=true
blur_radius=32
blur_darkness=0.6
font=JetBrainsMono Nerd Font
fontSize=11
cursor=Adwaita
loginBoxColor=#26ffffff
loginBoxRounding=20
loginBoxBorderColor=#66ffffff
loginBoxBorderSize=2
textColor=#ffffff
placeholderColor=#80ffffff
accentColor=#dcdcdc
hoverColor=#40ffffff
